version: '3'
services:
  db:
    image: mysql:5.7
    privileged: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "6378:6379"        
  web:
    build: .
    volumes:
      - .:/base-rails6-ruby2.7
    ports:
      - "3000:3000"  
    environment:
      - REDIS_SERVER=base-rails6-ruby2.7_redis_1
      - APP_HOST=localhost  
    depends_on:
      - db
      - redis 
    stdin_open: true
    tty: true
